apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-crud-api
  template:
    metadata:
      labels:
        app: go-crud-api
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.0-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/
              name: nginx-config
              readOnly: true
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
        - name: go-crud-api
          image: go-crud-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

      volumes:
        - name: nginx-config
          configMap:
            name: confnginx
